export const styles = {
  card: {
    background: "#fff",
    borderRadius: 16,
    border: "0.5px solid #e0dfd9",
    padding: "2.5rem 2rem",
  },
  iconWrap: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 1.5rem",
  },
  title: {
    fontSize: 20,
    fontWeight: 500,
    color: "#111",
    textAlign: "center" as const,
    marginBottom: "0.4rem",
  },
  sub: {
    fontSize: 14,
    color: "#888",
    textAlign: "center" as const,
    marginBottom: "1.5rem",
  },
  badgeSuccess: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 500,
    background: "#eaf4ea",
    color: "#2a7a2a",
  },
  badgeFailed: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 500,
    background: "#fdf2f2",
    color: "#b93232",
  },
  dot: { width: 6, height: 6, borderRadius: "50%" },
  itemsBox: {
    background: "#f5f4f0",
    borderRadius: 10,
    padding: "1rem",
    marginBottom: "1.5rem",
  },
  itemRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.5rem 0",
    borderBottom: "0.5px solid #e8e7e2",
  },
  itemName: { fontSize: 13, color: "#333" },
  itemQty: { fontSize: 12, color: "#aaa", marginTop: 2 },
  itemPrice: { fontSize: 13, fontWeight: 500, color: "#111" },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "0.75rem",
    marginTop: "0.25rem",
    borderTop: "0.5px solid #dddcd7",
  },
  totalLabel: { fontSize: 13, fontWeight: 500, color: "#111" },
  totalValue: { fontSize: 16, fontWeight: 500, color: "#111" },
  divider: {
    border: "none",
    borderTop: "0.5px solid #eeede8",
    margin: "1.5rem 0",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "0.75rem",
  },
  rowLabel: { fontSize: 13, color: "#888" },
  rowValue: { fontSize: 13, fontWeight: 500, color: "#111" },
  btnBlack: {
    width: "100%",
    padding: "0.75rem",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    border: "none",
    background: "#111",
    color: "#fff",
    marginBottom: "0.75rem",
  },
  btnOutline: {
    width: "100%",
    padding: "0.75rem",
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    background: "transparent",
    color: "#111",
    border: "0.5px solid #ccc",
  },
};
