export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f6f4ef",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem 1rem",
  },
  card: {
    background: "#fff",
    borderRadius: 14,
    border: "1px solid #e8e2d8",
    boxShadow: "0 18px 50px rgba(48, 43, 35, 0.08)",
    padding: "2rem",
  },
  iconWrap: {
    width: 58,
    height: 58,
    borderRadius: 18,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 1.25rem",
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    color: "#111",
    textAlign: "center" as const,
    marginBottom: "0.5rem",
  },
  sub: {
    fontSize: 14.5,
    color: "#65615a",
    lineHeight: 1.6,
    textAlign: "center" as const,
    marginBottom: "1.5rem",
  },
  badgeRow: {
    display: "flex",
    justifyContent: "center",
    marginBottom: "1.25rem",
  },
  badgeSuccess: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    background: "#eaf4ea",
    color: "#2a7a2a",
  },
  badgeFailed: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    background: "#fdf2f2",
    color: "#b93232",
  },
  dot: { width: 6, height: 6, borderRadius: "50%" },
  statusPanel: {
    background: "#171717",
    borderRadius: 12,
    color: "#fff",
    marginBottom: "1.25rem",
    padding: "1rem",
  },
  statusKicker: {
    color: "#c8c2b8",
    fontSize: 12,
    marginBottom: "0.35rem",
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: 700,
    marginBottom: "0.25rem",
  },
  statusText: {
    color: "#ddd7ce",
    fontSize: 13,
    lineHeight: 1.45,
    margin: 0,
  },
  itemsBox: {
    background: "#f8f6f1",
    borderRadius: 10,
    padding: "1rem",
    marginBottom: "1.5rem",
  },
  noticeBox: {
    background: "#fbf7ed",
    border: "0.5px solid #e7e4dc",
    borderRadius: 10,
    color: "#625a4d",
    fontSize: 13,
    lineHeight: 1.5,
    marginBottom: "1rem",
    padding: "0.85rem 1rem",
  },
  fallbackList: {
    display: "grid",
    gap: "0.55rem",
    margin: "0 0 1.5rem",
    padding: 0,
    listStyle: "none",
  },
  fallbackItem: {
    alignItems: "flex-start",
    color: "#555",
    display: "flex",
    fontSize: 13,
    gap: "0.55rem",
    lineHeight: 1.45,
  },
  fallbackBullet: {
    background: "#111",
    borderRadius: "50%",
    flex: "0 0 auto",
    height: 6,
    marginTop: 7,
    width: 6,
  },
  itemRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.5rem 0",
    borderBottom: "0.5px solid #e8e7e2",
  },
  itemName: { fontSize: 13, color: "#333" },
  itemQty: { fontSize: 12, color: "#aaa", marginTop: 2 },
  itemPrice: { fontSize: 13, fontWeight: 500, color: "#111" },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "0.75rem",
    marginTop: "0.25rem",
    borderTop: "0.5px solid #dddcd7",
  },
  totalLabel: { fontSize: 13, fontWeight: 500, color: "#111" },
  totalValue: { fontSize: 16, fontWeight: 500, color: "#111" },
  divider: {
    border: "none",
    borderTop: "0.5px solid #eeede8",
    margin: "1.5rem 0",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "1rem",
    marginBottom: "0.75rem",
  },
  rowLabel: { fontSize: 13, color: "#888" },
  rowValue: {
    fontSize: 13,
    fontWeight: 600,
    color: "#111",
    overflowWrap: "anywhere" as const,
    textAlign: "right" as const,
  },
  btnBlack: {
    width: "100%",
    padding: "0.85rem",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    border: "none",
    background: "#111",
    color: "#fff",
    marginBottom: "0.75rem",
  },
  btnOutline: {
    width: "100%",
    padding: "0.85rem",
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    background: "transparent",
    color: "#111",
    border: "0.5px solid #ccc",
  },
};
